language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t simple-node-ci --build-arg MISSING=${MISSING} .
  - docker tag simple-node-ci andrewserra/simple-node:latest

after_success:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push andrewserra/simple-node

